### ISSUE TITLE
Error when using require_relative with Ruby 1.9.2 and Rack 1.2.1

### ISSUE THREAD

**Issue by jammur** [rack/rack#115]
When using require_relative in my config.ru, I get an error with the following stack trace: 

```
config.ru:3:in `require_relative': cannot infer basepath (LoadError)
from config.ru:3:in `block in <main>'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `instance_eval'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `initialize'
from config.ru:1:in `new'
from config.ru:1:in `<main>'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `eval'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `parse_file'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:162:in `app'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:248:in `wrapped_app'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:213:in `start'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:100:in `start'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/bin/rackup:4:in `<top (required)>'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/bin/rackup:19:in `load'
from /Users/jamie/.rvm/gems/ruby-1.9.2-p136/bin/rackup:19:in `<main>'
```

**Comment by LiebeB** [comment]
Hey, guys! I've been struggling with this too (hope it's ok if I jump on this issue)...

I'm receiving this error:

An error occurred while loading ./spec/say_hello_spec.rb.
Failure/Error: require expand_path("../say_hello")
NoMethodError:
  undefined method `expand_path' for main:Object
# ./spec/say_hello_spec.rb:1:in `<top (required)>'
No examples found.
Finished in 0.00031 seconds (files took 0.14459 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

I'm not sure what to do to fix it... Have tried a few ways and no improvement :/
