### ISSUE TITLE
Can't deserialize Rack::Utils::HeaderHash

### ISSUE THREAD

**Issue by TurtleKitty** [rack/rack#1186]
I have a number of objects in the DB that were serialized from Rack::Utils::HeaderHash objects, and I can't seem to marshall them with the latest version (Ruby 2.4.1 with Rack 2.0.3).  I thought this might be a version incompatibility, as they were serialized with Ruby 2.2.4 and Rack 2.0.1, but it seems I can't even marshal objects I just serialized with the current version:

```
$ irb
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> require 'rack/utils'
=> true
irb(main):003:0> hh = Rack::Utils::HeaderHash.new( { foo: 2, bar: 3 } )
=> {:foo=>2, :bar=>3}
irb(main):004:0> dump = YAML.dump(hh)
=> "--- !ruby/hash-with-ivars:Rack::Utils::HeaderHash\nelements:\n  :foo: 2\n  :bar: 3\nivars:\n  :@names:\n    :foo: :foo\n    :bar: :bar\n"
irb(main):005:0> YAML.load(dump)
NoMethodError: undefined method `[]' for nil:NilClass
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/utils.rb:470:in `[]='
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:362:in `block in revive_hash'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:271:in `block in visit_Psych_Nodes_Mapping'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:268:in `each'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:268:in `each_slice'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:268:in `visit_Psych_Nodes_Mapping'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych/nodes/node.rb:38:in `to_ruby'
        from /Users/turtlekitty/.rbenv/versions/2.4.1/lib/ruby/2.4.0/psych.rb:253:in `load'
        from (irb):6
        from /Users/turtlekitty/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'

```

**Comment by goodniceweb** [comment]
Still an issue for me
@TurtleKitty any luck with resolving that?

**Comment by TurtleKitty** [comment]
Nope.  I went around it somehow.  I think it involved regular expressions in SQL updates to fix some things that had been serialized into a database field... for some reason.  Feel free to close this if no one else in the world cares. `^_^`

**Comment by jkowens** [comment]
Turns out this is probably an issue with the YAML parser Psych. 

See: https://github.com/ruby/psych/issues/315
