### ISSUE TITLE
ThreadError: deadlock; recursive locking

### ISSUE THREAD

**Issue by TiuTalk** [rack/rack#1244]
I'm running a **rails** `3.2.22.5` app with **rack** `1.4.7` on **Ruby** `2.4.3` and we noticed a bunch of **ThreadErros** happening.

Here is the backtrace of one if the exceptions, you can see more details [here, on the Sentry page](https://sentry.io/share/issue/45fd720c69de4b2aab11321fe09ef562/):

```shell
ThreadError: deadlock; recursive locking
  from rack/lock.rb:14:in `lock'
  from rack/lock.rb:14:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/static.rb:83:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/deflater.rb:13:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/cache/context.rb:140:in `forward'
  from rack/cache/context.rb:147:in `pass'
  from rack/cache/context.rb:159:in `invalidate'
  from rack/cache/context.rb:74:in `call!'
  from rack/cache/context.rb:51:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from skylight/middleware.rb:79:in `call'
  from rails/engine.rb:484:in `call'
  from rails/application.rb:231:in `call'
  from rails/railtie/configurable.rb:30:in `method_missing'
  from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception
```

And here is the rack middleware list:

```ruby
use Raven::Rack
use Rack::Cache
use Rack::Deflater
use ActionDispatch::Static
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use ActionDispatch::Head
use Rack::ConditionalGet
use Rack::ETag
use ActionDispatch::BestStandardsSupport
use Warden::Manager
use Rack::Attack
use Bullet::Rack
use OmniAuth::Strategies::Facebook
run StudySoup::Application.routes
```

Is there anything I should try before giving up and thinking it has to do with outdated `rack` version?

**Comment by rafaelfranca** [comment]
Hard to say. You are using an outdated version of rack and rails, so maybe you hit a bug that was already fixed. Also, usually this kind of issue is caused by a `Timeout.timeout` call raising exception at random places. Are you using `Timeout`?

**Comment by TiuTalk** [comment]
@rafaelfranca the exception goes away after we removed `Rack::Deflate` so I'm guessing it has to do with the `rack` version we are using 👍
