### ISSUE TITLE
Read error: #<NoMethodError: undefined method `each' for "":String>

### ISSUE THREAD

**Issue by noctivityinc** [rack/rack#1307]
Just updated to 2.0.5 and when running specs with rspec Im seeing the following:

```
Read error: #<NoMethodError: undefined method `each' for "":String>
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/rack-2.0.5/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/rack-2.0.5/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/rack-2.0.5/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/rack-2.0.5/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/rack-2.0.5/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/puma-3.12.0/lib/puma/server.rb:791:in `handle_request'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/Users/jlippiner/.rvm/gems/ruby-2.5.1@dmvcs/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by tristanoneil** [comment]
FWIW I ran into a similar issue but it was because I had some middleware that was returning a `String` as the response body. I don't have enough insight on rack internals but my guess is this is just not an expected response type. @noctivityinc perhaps check what middleware you have in place and see if somewhere along the line a `String` is being returned?

**Comment by rafaelfranca** [comment]
Yes, the body needs to respond to `#each`. If your middleware/application is returning a string it is not compatible with Rack. Closing since this is nor a rack issue. Thank you for reporting.
