### ISSUE TITLE
`NoMethodError: undefined method `reject' for nil:NilClass` when running `rails test`.

### ISSUE THREAD

**Issue by HansBug** [rack/rack#1582]
This is error message when running `rails test`.

```
ERROR["test_root_workspace_index", #<Minitest::Reporters::Suite:0x0000000012006628 @name="RootControllerTest">, 21.047404149000613]
 test_root_workspace_index#RootControllerTest (21.05s)
Minitest::UnexpectedError:         NoMethodError: undefined method `reject' for nil:NilClass
            test/controllers/root_controller_test.rb:46:in `block in <class:RootControllerTest>'

ERROR["test_workspace_token_create", #<Minitest::Reporters::Suite:0x000000001086ceb8 @name="WorkspaceControllerTest">, 21.075543044999904]
 test_workspace_token_create#WorkspaceControllerTest (21.08s)
Minitest::UnexpectedError:         NoMethodError: undefined method `reject' for nil:NilClass
            test/controllers/workspace_controller_test.rb:148:in `block in <class:WorkspaceControllerTest>'

ERROR["test_workspace_token_enable", #<Minitest::Reporters::Suite:0x000000001088ee28 @name="WorkspaceControllerTest">, 21.080282165000426]
 test_workspace_token_enable#WorkspaceControllerTest (21.08s)
Minitest::UnexpectedError:         NoMethodError: undefined method `reject' for nil:NilClass
            test/controllers/workspace_controller_test.rb:275:in `block in <class:WorkspaceControllerTest>'

ERROR["test_workspace_current_token_profile", #<Minitest::Reporters::Suite:0x0000000010816338 @name="WorkspaceControllerTest">, 21.086764450999908]
 test_workspace_current_token_profile#WorkspaceControllerTest (21.09s)
Minitest::UnexpectedError:         NoMethodError: undefined method `reject' for nil:NilClass
            test/controllers/workspace_controller_test.rb:32:in `block in <class:WorkspaceControllerTest>'
```

I ran `rails test` yesterday, with gems below, no failures or errors.

* rails, 5.1.7
* rack 2.1.2
* ruby 2.4.0

Then I upgrade to gems below, the errors above (**all the tests with controller**) are thrown.

* rails 5.1.7
* rack 2.2.0
* ruby 2.5.7

After that, I downgrade rack to version `2.1.2` (ruby's version is still `2.5.7`), no failures or errors.

**Comment by HansBug** [comment]
I just compare the set of gems yesterday and now (both are runnable), the only difference is the version of gem `rack` (from 2.1.2 to 2.2.0).

**Comment by ioquatix** [comment]
Can you try 2.2.1

**Comment by HansBug** [comment]
Just not I upgrade rack from `2.2.0` to `2.2.1`. Now it can run properly.

Thanks! :)

**Comment by ioquatix** [comment]
Thanks for confirming the latest version is working correctly.
