### ISSUE TITLE
Test failure with rack 2.0.8

### ISSUE THREAD

**Issue by utkarsh2102** [rack/rack#1616]
Hi,

For some reasons, I am supposed to use rack 2.0.8.
With that, I am getting the following test failure:
```
Finished in 5.229614s, 191.7924 runs/s, 693.9327 assertions/s.

  1) Error:
Rack::Session::Pool#test_0007_omits cookie with :defer option:
RuntimeError: 
    /<<PKGBUILDDIR>>/lib/rack/session/abstract/id.rb:31:in `to_s'
    /<<PKGBUILDDIR>>/lib/rack/session/abstract/id.rb:384:in `commit_session'
    /<<PKGBUILDDIR>>/lib/rack/session/abstract/id.rb:261:in `context'
    /<<PKGBUILDDIR>>/lib/rack/utils.rb:421:in `call'
    /<<PKGBUILDDIR>>/lib/rack/mock.rb:74:in `request'
    /<<PKGBUILDDIR>>/lib/rack/mock.rb:56:in `get'
    /<<PKGBUILDDIR>>/test/spec_session_pool.rb:140:in `block (2 levels) in <top (required)>'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:98:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:195:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:95:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:270:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:94:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:211:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:93:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:1029:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:339:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:326:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:352:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:324:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:141:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:68:in `block in autorun'

1003 runs, 3629 assertions, 0 failures, 1 errors, 2 skips
```

**Comment by jeremyevans** [comment]
You could try running 2.0.9, that's the latest release in the 2.0 series.  It should hopefully fix this issue.
