### ISSUE TITLE
Getting unless headers[CACHE_CONTROL] error in a Rails app

### ISSUE THREAD

**Issue by thomasdarde** [rack/rack#1698]
I'm seeing the same error as the one described here .

https://stackoverflow.com/questions/62889544/rails-actual-error-not-shown-showing-rack-etag-error-with-headers-array

This happens since a few days, but I can't find the reason why

**Comment by jeremyevans** [comment]
Can you please post a full backtrace?  This may be related to #1619, but it's hard to tell without a backtrace.

**Comment by thomasdarde** [comment]
Here is a backtrace when removing the etag middleware as described in #1619 

`config.middleware.delete Rack::ETag`

It happens with a simple `raise` in the code 

```
NoMethodError (undefined method `each' for nil:NilClass):

rack (2.2.3) lib/rack/utils.rb:429:in `initialize'
rack (2.2.3) lib/rack/utils.rb:422:in `new'
rack (2.2.3) lib/rack/utils.rb:422:in `[]'
rack (2.2.3) lib/rack/conditional_get.rb:28:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
honeybadger (4.7.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.7.0) lib/honeybadger/agent.rb:401:in `with_rack_env'
honeybadger (4.7.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.7.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.7.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by jeremyevans** [comment]
It sounds like app is rescuing the exception but returning the headers as nil instead of an enumerable.  This violates the rack spec, and the behavior of middleware that ship with rack is undefined in such cases.  If you can reproduce this using just rack without Rails, please post a minimal self contained reproducible example.

**Comment by thomasdarde** [comment]
Ok,  I will try to work on this , thanks a lot for the explanations, maybe some other users will get here googling for a solution. I will update the ticket once the error fixed

**Comment by thomasdarde** [comment]
I found the issue, linked to the pdfkit gem , version 0.8.4.2 was ok, version 0.8.4.3.1 causes this mess.
I will close the issue, thank you for giving me the motivation to search outside of rack

**Comment by julienchabanon** [comment]
@thomasdarde Hi there! I am having the exact same as you but I am not using pdfkit gem. How did you troubleshoot this to find the culprit gem? thank you

**Comment by thomasdarde** [comment]
Hi @julienchabanon , I think I did just check the recent gemfile changes via git to try to revert them

**Comment by julienchabanon** [comment]
I found the culprit! It was omniauth. Downgrading omniauth from 2.0.4 to 1.9.1 did solve the problem.
