### ISSUE TITLE
<RegexpError: failed to allocate memory: /\A[\[\]]*([^\[\]]+)\]*/>  error during upload of file

### ISSUE THREAD

**Issue by Fivell** [rack/rack#1704]
steps to reproduce
 1) dd of=data_178mb if=/dev/zero bs=1M count=178
 2) curl -v --data-binary @data_178mb https://localhost:3000/bulk_create_verification
 3) 

```
2020-08-28 13:11:26 +0000: Rack app error handling request { POST /bulk_create_verification }
#<RegexpError: failed to allocate memory: /\A[\[\]]*([^\[\]]+)\]*/>
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/query_parser.rb:87:in `normalize_params'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/query_parser.rb:73:in `block in parse_nested_query'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/query_parser.rb:70:in `each'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/query_parser.rb:70:in `parse_nested_query'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/request.rb:490:in `parse_query'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/request.rb:364:in `POST'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/method_override.rb:45:in `method_override_param'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/method_override.rb:29:in `method_override'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/method_override.rb:17:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/runtime.rb:24:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/rack-2.1.4/lib/rack/sendfile.rb:113:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/utf8-cleaner-0.2.5/lib/utf8-cleaner/middleware.rb:21:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/sentry-raven-2.9.0/lib/raven/integrations/rack.rb:51:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/opt/panel/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by senid231** [comment]
reproduce with 1mb file

**Comment by jeremyevans** [comment]
I'm trying to write a failing spec for this, but it doesn't seem to fail on the master branch.  Can you reproduce this on master?  On master, an all zero input of up to 64KB works, resulting in a key of all zeros with one fewer byte.  Above 64KB fails in the default configuration with `RangeError: exceeded available parameter key space`

Specs:

```ruby
  it "handles parsing all ASCII NUL input under 64KB" do
    length = 65000
    mr = Rack::MockRequest.env_for("/",
      "REQUEST_METHOD" => 'POST',
      :input => "\0"*length)
    req = make_request mr
    req.query_string.must_equal ""
    req.GET.must_be :empty?
    req.POST.keys.must_equal ["\0"*(length-1)]
  end

  it "raises range error for all ASCII NUL input above 64KB" do
    length = 66000
    mr = Rack::MockRequest.env_for("/",
      "REQUEST_METHOD" => 'POST',
      :input => "\0"*length)
    req = make_request mr
    req.query_string.must_equal ""
    req.GET.must_be :empty?
    proc{req.POST}.must_raise RangeError
  end
```

**Comment by ioquatix** [comment]
@jeremyevans since we removed the key space limit, does this still fail the same way?

**Comment by jeremyevans** [comment]
On my machine, I can reproduce the RegexpError with 32MB upload, but not with 16MB upload.  How do we want to handle this?  Should we really try to parse a 16MB parameter name?  For better or worse, the key space limit we just removed at least prevented this particular issue.  Maybe we should have a similar limit, but that specifies the maximum length/bytesize of individual parameter names (key space limit was similar, but not exactly that)?

**Comment by jeremyevans** [comment]
I recommend we fix this issue by avoiding using regexps for parsing parameter keys.  I submitted a pull request for that: #1797
