### ISSUE TITLE
ETag middleware no longer handles a Rack::Response body of [nil] 

### ISSUE THREAD

**Issue by stanhu** [rack/rack#1712]
Prior to Rack v2.1.0, a `Rack::Response` initialized with `[nil]` would be handled gracefully because `to_s` would be run on each element: https://github.com/rack/rack/blob/85684323f8f58409e717af91e446d257d496f8b8/lib/rack/response.rb#L40-L43

Now that https://github.com/rack/rack/pull/1434/files has merged, if `[nil]` is used, the ETag calculations fails with:

```
NoMethodError (undefined method `empty?' for nil:NilClass):
rack (2.1.4) lib/rack/etag.rb:70:in `block in digest_body'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `block in each'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `each'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `each'
rack (2.1.4) lib/rack/etag.rb:68:in `digest_body'
rack (2.1.4) lib/rack/etag.rb:31:in `call'
rack (2.1.4) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.4) lib/rack/head.rb:14:in `call'
actionpack (6.0.3.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
```

Is `[nil]` a valid input? If so, does it make sense to fix this in `Rack::Response` so ETag calculations use `''`, or fix in the ETag handler?

Related issue in Grape: https://github.com/ruby-grape/grape/issues/2118

**Comment by stanhu** [comment]
Hmm, this might have been fixed by 549412368.

**Comment by stanhu** [comment]
Ok, I think I finally understand the problem:

1. Grape's own Rack middleware (`base.rb`) sends essentially sends something like `Rack::Response.new([nil], 200, {})`: https://github.com/ruby-grape/grape/blob/0e0c1550999bd1d80618e534880391796f2d9a98/lib/grape/middleware/base.rb#L62
1. `response.body` gets passed to `Rack::Etag`: https://github.com/rack/rack/blob/5ce5b2ccb151c62652e25b4711218ede11497cc3/lib/rack/etag.rb#L27
1. `Rack::Etag` iterates on the `Array` and calls `String#empty?` on all elements: https://github.com/rack/rack/blob/5ce5b2ccb151c62652e25b4711218ede11497cc3/lib/rack/etag.rb#L70

As a result, with Rack v2.1.4, we get:

```
NoMethodError (undefined method `empty?' for nil:NilClass):

rack (2.1.4) lib/rack/etag.rb:70:in `block in digest_body'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `block in each'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `each'
rack (2.1.4) lib/rack/body_proxy.rb:34:in `each'
rack (2.1.4) lib/rack/etag.rb:68:in `digest_body'
rack (2.1.4) lib/rack/etag.rb:31:in `call'
rack (2.1.4) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.4) lib/rack/head.rb:14:in `call'
```

Prior to Rack v2.1.0, the constructor of `Rack::Response` called `to_str` on all the elements of the `Array`. However, after Rack v2.1.4, https://github.com/rack/rack/pull/1434/files lazily writes out the response body. The ETag middleware doesn't actually trigger the write, so instead it gets the raw response body (`[nil]`). 

I think the simplest fix is to make the ETag middleware behave: https://github.com/rack/rack/pull/1713.

**Comment by stanhu** [comment]
Closing due to https://github.com/rack/rack/pull/1713#issuecomment-709379195.
