### ISSUE TITLE
Time header issue in deflater

### ISSUE THREAD

**Issue by niedfelj** [rack/rack#1737]
I'm running into a weird bug with Rack::Deflater throwing this error:

ArgumentError not RFC 2616 compliant date: "Tue, 25 Feb 2020 11:51:53 +0000"

From

rack (2.2.3) lib/rack/deflater.rb in call at line 67

It appears to be related to this Ruby bug https://bugs.ruby-lang.org/issues/10733, with resolution to be to always force the header string to be UTF-8

"Mon, 19 Jan 2015 08:43:19 GMT".encode 'UTF-8'

It seems to only happen when requests are coming through the Cloudflare proxy/cdn. For now I've removed rack deflater from my stack. More details on the exception can be found in Sentry:

https://sentry.io/share/issue/b3ba8ace0b3a4143aea925f81fac47a6/

Let me know if you'd like me to test a fork of this with that encoding on the header to see if it resolves the issue.

**Comment by jeremyevans** [comment]
It would be great if you could put together a minimal self contained example showing this issue (or a failing test for it).

**Comment by jeremyevans** [comment]
Closing due to no response in almost a year, and our inability to replicate the failure.  If you can reproduce this, please provide a reproducible example.

**Comment by thadeu** [comment]
Hey guys, I would to re-open this issue because I'm getting the same error.

I'm running the Rails application and I'm using `config.middleware.use Rack::Deflater` in my configurations.

Stack trace above.

```
Started GET "/sidekiq/images/favicon.ico" for ::1 at 2025-02-04 15:40:47 -0300
  AdminUser Load (0.6ms)  SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = 26 ORDER BY "admin_users"."id" ASC LIMIT 1

ArgumentError (not RFC 2616 compliant date: "Sex, 27 Dez 2024 18:26:57 GMT"):

/Users/thadeu/.rbenv/versions/3.2.3/lib/ruby/3.2.0/time.rb:596:in `httpdate'
rack (2.2.10) lib/rack/deflater.rb:67:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.10) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.10) lib/rack/etag.rb:27:in `call'
rack (2.2.10) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.10) lib/rack/head.rb:12:in `call'
actionpack (7.1.5.1) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.5.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.10) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.10) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.5.1) lib/active_record/migration.rb:655:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.5.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.5.1) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.5.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.5.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.5.1) lib/active_support/tagged_logging.rb:139:in `block in tagged'
activesupport (7.1.5.1) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.5.1) lib/active_support/tagged_logging.rb:139:in `tagged'
activesupport (7.1.5.1) lib/active_support/broadcast_logger.rb:241:in `method_missing'
railties (7.1.5.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
request_store (1.7.0) lib/request_store/middleware.rb:19:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (2.2.10) lib/rack/method_override.rb:24:in `call'
rack (2.2.10) lib/rack/runtime.rb:22:in `call'
activesupport (7.1.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.5.1) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (2.2.10) lib/rack/sendfile.rb:110:in `call'
actionpack (7.1.5.1) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
secure_headers (6.7.0) lib/secure_headers/middleware.rb:11:in `call'
hirefire-resource (0.4.0) lib/hirefire/middleware.rb:41:in `call'
webpacker (3.5.0) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.7.7) lib/rack/proxy.rb:87:in `call'
railties (7.1.5.1) lib/rails/engine.rb:536:in `call'
rack (2.2.10) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.10) lib/rack/urlmap.rb:58:in `each'
rack (2.2.10) lib/rack/urlmap.rb:58:in `call'
rack-attack (6.7.0) lib/rack/attack.rb:103:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
logging (2.4.0) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by thadeu** [comment]
Could I re-open this issue? @jeremyevans

**Comment by jeremyevans** [comment]
Thanks for the full backtrace.  This seems like it would still be reproducible on master.  I'll reopen and send a pull request.

**Comment by thadeu** [comment]
@jeremyevans Thanks a lot.

**Comment by thadeu** [comment]
@jeremyevans For now, how can I create a workaround to this problem in my codebase?

**Comment by jeremyevans** [comment]
This should only happen if your application is providing an invalid last-modified header.  Best fix would be to fix the application.  If you cannot fix the application, adding a middleware that removes invalid last-modified response headers would also work, but you would need to make sure Rack::Deflater wraps that, and not the other way around.

I submitted a pull request to fix this: #2278

**Comment by thadeu** [comment]
> This should only happen if your application is providing an invalid last-modified header. Best fix would be to fix the application. If you cannot fix the application, adding a middleware that removes invalid last-modified response headers would also work, but you would need to make sure Rack::Deflater wraps that, and not the other way around.
> 
> I submitted a pull request to fix this: [#2278](https://github.com/rack/rack/pull/2278)

Ok, I got it.

For now, I just added a condition to use Rack::Deflater or not, in my middleware.

```rb
config.middleware.use(
  Rack::Deflater,
  if: ->(env, _, _, _) { %r{/sidekiq}.match?(env['PATH_INFO']) }
)
```

It works perfectly, until the new release get launch.

**Comment by jeremyevans** [comment]
After discussion in #2278, I'm going to close this.  This is definitely an application bug, and there is no requirement that Rack::Deflater work around application bugs.  @thadeu you'll need to find out why your application is issuing invalid `last-modified` headers and fix the issue, or workaround the issue yourself by removing the last-modified header in an inner middleware.  Any fix would not have affected you, since there is no way we would backport the fix to Rack 2.2 in any case.

**Comment by ioquatix** [comment]
@thadeu can you show us your `bin/rails middleware`
