### ISSUE TITLE
Rack::MockRequest should be parsing 'expires' to a Time instance

### ISSUE THREAD

**Issue by speckins** [rack/rack#1758]
I encountered the error

	NoMethodError: undefined method `gmtime' for "Thu, 29 Jun 2023 10:44:23 GMT":String

from the following expectation (which was failing):

	_(last_response).must_be :redirection?

Evidently this was due to the `CGI::Cookie#inspect` method being called.

[CGI::Cookie#inspect](https://github.com/ruby/cgi/blob/c42f91561548f29416c7b6d89020983b519903b1/lib/cgi/cookie.rb#L143) calls `#to_s`, which passes the value of 'expires' to [CGI.rfc1123_date](https://github.com/ruby/cgi/blob/c42f91561548f29416c7b6d89020983b519903b1/lib/cgi/util.rb#L193), which expects a Time object (or at least something that responds to `#gmtime`).  While `Rack::MockRequest#identify_cookie_attributes` sets 'expires' to a Time instance if 'max-age' is set, it doesn't parse 'expires' itself into a Time instance.

If I monkeypatch the code like so, it works as expected:

```ruby
module FixCookies
  private

  def identify_cookie_attributes(cookie_filling)
    super.tap do |cookie_attributes|
      if cookie_attributes['expires'].is_a? String
        cookie_attributes['expires'] = Time.parse cookie_attributes['expires']
      end
    end
  end
end

Rack::MockResponse.prepend FixCookies
```

**Comment by speckins** [comment]
Here's a minimal demonstration of the issue:
```
$ irb -r rack/mock

irb(main):001:0> Rack::MockResponse.new(204, {'Set-Cookie' => "foo=bar; max-age=0"}, ['']).cookies.inspect
=> "{\"foo\"=>#<CGI::Cookie: \"foo=bar; path=; expires=Wed, 30 Jun 2021 13:55:43 GMT\">}"

irb(main):002:0> Rack::MockResponse.new(204, {'Set-Cookie' => "foo=bar; expires=#{Time.now.httpdate}"}, ['']).cookies.inspect
Traceback (most recent call last):
        8: from ~/.rubies/ruby-2.7.1/bin/irb:23:in `<main>'
        7: from ~/.rubies/ruby-2.7.1/bin/irb:23:in `load'
        6: from ~/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        5: from (irb):13
        4: from (irb):13:in `inspect'
        3: from ~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/cgi/cookie.rb:176:in `inspect'
        2: from ~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/cgi/cookie.rb:143:in `to_s'
        1: from ~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/cgi/util.rb:188:in `rfc1123_date'
NoMethodError (undefined method `gmtime' for "Wed, 30 Jun 2021 13:55:47 GMT":String)
```
I'll open a PR.
