### ISSUE TITLE
undefined method `each' for nil:NilClass in middleware after bundle update

### ISSUE THREAD

**Issue by julienchabanon** [rack/rack#1783]
This error occurs since a bundle update. I have no way to track down which gem could be the error just with this log. It also happens on both ruby 2.7.X and 3.0.X. It seems to happens on every http call received and I cant troubleshoot in application level as the error reach the middleware first.

```
NoMethodError (undefined method 'each' for nil:NilClass):
  
rack (2.2.3) lib/rack/utils.rb:429:in 'initialize'
rack (2.2.3) lib/rack/utils.rb:422:in 'new'
rack (2.2.3) lib/rack/utils.rb:422:in '[]'
rack (2.2.3) lib/rack/deflater.rb:45:in 'call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in 'call'
rack (2.2.3) lib/rack/etag.rb:27:in 'call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in 'call'
rack (2.2.3) lib/rack/head.rb:12:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/http/permissions_policy.rb:22:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in 'call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in 'context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/cookies.rb:689:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in 'block in call'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:98:in 'run_callbacks'
actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in 'call'
sentry-rails (4.8.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in 'call'
sentry-ruby-core (4.8.1) lib/sentry/rack/capture_exceptions.rb:25:in 'block in call'
sentry-ruby-core (4.8.1) lib/sentry/hub.rb:58:in 'with_scope'
sentry-ruby-core (4.8.1) lib/sentry-ruby.rb:202:in 'with_scope'
sentry-ruby-core (4.8.1) lib/sentry/rack/capture_exceptions.rb:16:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in 'call'
railties (6.1.4.1) lib/rails/rack/logger.rb:37:in 'call_app'
railties (6.1.4.1) lib/rails/rack/logger.rb:26:in 'block in call'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in 'block in tagged'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:37:in 'tagged'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in 'tagged'
railties (6.1.4.1) lib/rails/rack/logger.rb:26:in 'call'
sprockets-rails (3.4.1) lib/sprockets/rails/quiet_assets.rb:13:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in 'call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/request_id.rb:26:in 'call'
rack (2.2.3) lib/rack/method_override.rb:24:in 'call'
rack (2.2.3) lib/rack/runtime.rb:22:in 'call'
activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/static.rb:24:in 'call'
rack (2.2.3) lib/rack/sendfile.rb:110:in 'call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/host_authorization.rb:98:in 'call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in 'call'
railties (6.1.4.1) lib/rails/engine.rb:539:in 'call'
railties (6.1.4.1) lib/rails/railtie.rb:207:in 'public_send'
railties (6.1.4.1) lib/rails/railtie.rb:207:in 'method_missing'
puma (5.5.2) lib/puma/configuration.rb:249:in 'call'
puma (5.5.2) lib/puma/request.rb:77:in 'block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in 'with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in 'handle_request'
puma (5.5.2) lib/puma/server.rb:447:in 'process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in 'block in spawn_thread'
```

My Gemfile.lock

```PATH
  remote: local_gems
  specs:
    cloudflare (4.3.1)
      async-rest (~> 0.12.3)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.4.1)
      actionpack (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.4.1)
      actionpack (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      mail (>= 2.7.1)
    actionmailer (6.1.4.1)
      actionpack (= 6.1.4.1)
      actionview (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.4.1)
      actionview (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.4.1)
      actionpack (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      nokogiri (>= 1.8.5)
    actionview (6.1.4.1)
      activesupport (= 6.1.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    active_model_otp (2.3.1)
      activemodel
      rotp (~> 6.2.0)
    activejob (6.1.4.1)
      activesupport (= 6.1.4.1)
      globalid (>= 0.3.6)
    activemodel (6.1.4.1)
      activesupport (= 6.1.4.1)
    activerecord (6.1.4.1)
      activemodel (= 6.1.4.1)
      activesupport (= 6.1.4.1)
    activestorage (6.1.4.1)
      actionpack (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      marcel (~> 1.0.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    akami (1.3.1)
      gyoku (>= 0.4.0)
      nokogiri
    annotate (3.1.1)
      activerecord (>= 3.2, < 7.0)
      rake (>= 10.4, < 14.0)
    asterisk-ajam (0.0.2)
      libxml-ruby
    async (1.30.1)
      console (~> 1.10)
      nio4r (~> 2.3)
      timers (~> 4.1)
    async-http (0.56.5)
      async (>= 1.25)
      async-io (>= 1.28)
      async-pool (>= 0.2)
      protocol-http (~> 0.22.0)
      protocol-http1 (~> 0.14.0)
      protocol-http2 (~> 0.14.0)
    async-io (1.32.2)
      async
    async-pool (0.3.9)
      async (>= 1.25)
    async-rest (0.12.4)
      async-http (~> 0.42)
      protocol-http (~> 0.7)
    bcrypt (3.1.16)
    blanket_wrapper (3.0.2)
      httparty
      recursive-open-struct
    bootstrap-sass (2.3.0.0)
      sass (~> 3.2)
    bson (1.12.5)
    bson_ext (1.12.5)
      bson (~> 1.12.5)
    builder (3.2.4)
    byebug (11.1.3)
    cancancan (3.3.0)
    cane (3.0.0)
      parallel
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    chronic (0.10.2)
    chronic_duration (0.10.6)
      numerizer (~> 0.1.1)
    coderay (1.1.3)
    coffee-rails (5.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 5.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorize (0.8.1)
    concurrent-ruby (1.1.9)
    connection_pool (2.2.5)
    console (1.14.0)
      fiber-local
    crack (0.4.5)
      rexml
    crass (1.0.6)
    credit_card_sanitizer (0.6.8)
      luhn_checksum (~> 0.1)
      tracking_number (~> 0.10.3)
    database_cleaner (2.0.1)
      database_cleaner-active_record (~> 2.0.0)
    database_cleaner-active_record (2.0.1)
      activerecord (>= 5.a)
      database_cleaner-core (~> 2.0.0)
    database_cleaner-core (2.0.1)
    declarative (0.0.20)
    didww-client (0.1.1)
      savon (~> 2.11.1)
    diff-lcs (1.4.4)
    docile (1.4.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    doorkeeper (5.5.2)
      railties (>= 5)
    down (5.2.4)
      addressable (~> 2.8)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    erubi (1.10.0)
    erubis (2.7.0)
    eventmachine (1.2.7)
    excon (0.88.0)
    execjs (2.8.1)
    factory_bot (6.2.0)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faker (2.19.0)
      i18n (>= 1.6, < 2)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    fast_gettext (1.8.0)
    ffi (1.15.4)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    fiber-local (1.0.0)
    fog-core (2.2.4)
      builder
      excon (~> 0.71)
      formatador (~> 0.2)
      mime-types
    fog-json (1.2.0)
      fog-core
      multi_json (~> 1.10)
    fog-openstack (1.0.11)
      fog-core (~> 2.1)
      fog-json (>= 1.0)
      ipaddress (>= 0.8)
    font-awesome-sass (5.15.1)
      sassc (>= 1.11)
    formatador (0.3.0)
    gapic-common (0.7.0)
      faraday (~> 1.3)
      google-protobuf (~> 3.14)
      googleapis-common-protos (>= 1.3.11, < 2.a)
      googleapis-common-protos-types (>= 1.0.6, < 2.a)
      googleauth (>= 0.17.0, < 2.a)
      grpc (~> 1.36)
    gcm (0.1.1)
      httparty
      json
    gelf (3.1.0)
      json
    gemoji (3.0.1)
    gems (1.2.0)
    gettext (3.4.1)
      locale (>= 2.0.5)
      text (>= 1.3.0)
    gettext_i18n_rails (1.8.1)
      fast_gettext (>= 0.9.0)
    git (1.9.1)
      rchardet (~> 1.8)
    globalid (1.0.0)
      activesupport (>= 5.0)
    google-api-client (0.53.0)
      google-apis-core (~> 0.1)
      google-apis-generator (~> 0.1)
    google-apis-bigquery_v2 (0.21.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-core (0.4.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-discovery_v1 (0.7.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-drive_v3 (0.16.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-generator (0.4.0)
      activesupport (>= 5.0)
      gems (~> 1.2)
      google-apis-core (>= 0.4, < 2.a)
      google-apis-discovery_v1 (~> 0.5)
      thor (>= 0.20, < 2.a)
    google-apis-sheets_v4 (0.10.0)
      google-apis-core (>= 0.4, < 2.a)
    google-cloud-bigquery (1.38.0)
      concurrent-ruby (~> 1.0)
      google-apis-bigquery_v2 (~> 0.1)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.2.0)
    google-cloud-speech (0.41.0)
      google-gax (~> 1.8)
      googleapis-common-protos (>= 1.3.9, < 2.0)
      googleapis-common-protos-types (>= 1.0.4, < 2.0)
    google-cloud-text_to_speech (1.2.2)
      google-cloud-core (~> 1.6)
      google-cloud-text_to_speech-v1 (>= 0.0, < 2.a)
      google-cloud-text_to_speech-v1beta1 (>= 0.0, < 2.a)
    google-cloud-text_to_speech-v1 (0.4.4)
      gapic-common (>= 0.7, < 2.a)
      google-cloud-errors (~> 1.0)
    google-cloud-text_to_speech-v1beta1 (0.6.4)
      gapic-common (>= 0.7, < 2.a)
      google-cloud-errors (~> 1.0)
    google-cloud-translate (3.2.2)
      google-cloud-core (~> 1.6)
      google-cloud-translate-v2 (>= 0.0, < 2.a)
      google-cloud-translate-v3 (>= 0.0, < 2.a)
    google-cloud-translate-v2 (0.3.1)
      faraday (>= 0.17.3, < 2.a)
      google-cloud-core (~> 1.6)
      googleapis-common-protos (>= 1.3.10, < 2.a)
      googleapis-common-protos-types (>= 1.0.5, < 2.a)
      googleauth (>= 0.16.2, < 2.a)
    google-cloud-translate-v3 (0.4.1)
      gapic-common (>= 0.7, < 2.a)
      google-cloud-errors (~> 1.0)
    google-gax (1.8.2)
      google-protobuf (~> 3.9)
      googleapis-common-protos (>= 1.3.9, < 2.0)
      googleapis-common-protos-types (>= 1.0.4, < 2.0)
      googleauth (~> 0.9)
      grpc (~> 1.24)
      rly (~> 0.2.3)
    google-protobuf (3.19.1-x86_64-linux)
    google_drive (3.0.7)
      google-apis-drive_v3 (>= 0.5.0, < 1.0.0)
      google-apis-sheets_v4 (>= 0.4.0, < 1.0.0)
      googleauth (>= 0.5.0, < 1.0.0)
      nokogiri (>= 1.5.3, < 2.0.0)
    googleapis-common-protos (1.3.12)
      google-protobuf (~> 3.14)
      googleapis-common-protos-types (~> 1.2)
      grpc (~> 1.27)
    googleapis-common-protos-types (1.3.0)
      google-protobuf (~> 3.14)
    googleauth (0.17.1)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.15)
    grpc (1.41.1-x86_64-linux)
      google-protobuf (~> 3.17)
      googleapis-common-protos-types (~> 1.0)
    guard (2.18.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (>= 1.0.12, < 2.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.13.0)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-spork (2.1.0)
      childprocess (>= 0.2.3)
      guard (~> 2.0)
      guard-compat (~> 1.0)
      spork (>= 0.8.4)
    gyoku (1.3.1)
      builder (>= 2.1.2)
    hashdiff (1.0.1)
    hashie (5.0.0)
    highline (2.0.3)
    hitimes (1.3.1)
    http (5.0.4)
      addressable (~> 2.8)
      http-cookie (~> 1.0)
      http-form_data (~> 2.2)
      llhttp-ffi (~> 0.4.0)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    http-form_data (2.3.0)
    http_parser.rb (0.8.0)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    httpi (2.5.0)
      rack
      socksify
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    ipaddress (0.8.3)
    jbuilder (2.11.3)
      activesupport (>= 5.0.0)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (2.6.1)
    json-schema (2.8.1)
      addressable (>= 2.4)
    jwt (1.5.6)
    libxml-ruby (3.2.1)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    llhttp-ffi (0.4.0)
      ffi-compiler (~> 1.0)
      rake (~> 13.0)
    locale (2.1.3)
    lograge (0.11.2)
      actionpack (>= 4)
      activesupport (>= 4)
      railties (>= 4)
      request_store (~> 1.0)
    loofah (2.12.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    luhn_checksum (0.1.1)
    lumberjack (1.2.8)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    memoist (0.16.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.1115)
    mimemagic (0.3.10)
      nokogiri (~> 1)
      rake
    mini_mime (1.1.2)
    minitest (5.14.4)
    monit-client (0.3.2)
    msgpack (1.4.2)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    mysql2 (0.5.3)
    nenv (0.3.0)
    net_http_unix (0.2.2)
    nio4r (2.5.8)
    nokogiri (1.12.5-x86_64-linux)
      racc (~> 1.4)
    nori (2.6.0)
    notiffany (0.1.3)
      nenv (~> 0.1)
      shellany (~> 0.0)
    numerizer (0.1.1)
    oauth2 (1.4.7)
      faraday (>= 0.8, < 2.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (2.0.4)
      hashie (>= 3.4.6)
      rack (>= 1.6.2, < 3)
      rack-protection
    omniauth-google-oauth2 (0.5.4)
      jwt (>= 1.5)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.5)
    omniauth-kerberos (0.3.0)
      omniauth-multipassword
      timfel-krb5-auth (~> 0.8)
    omniauth-linkedin-oauth2 (1.0.0)
      omniauth-oauth2
    omniauth-multipassword (2.0.0.rc1)
      omniauth (~> 2.0)
    omniauth-oauth2 (1.7.2)
      oauth2 (~> 1.4)
      omniauth (>= 1.9, < 3)
    opensips-mi (0.0.11)
      socketry (~> 0.5)
      xmlrpc (~> 0.3)
    optimist (3.0.1)
    options (2.3.2)
    os (1.1.4)
    parallel (1.21.0)
    permanent_records (3.1.6)
      activerecord (>= 3.0.0)
    phonelib (0.6.54)
    power_assert (2.0.1)
    progress_bar (1.3.3)
      highline (>= 1.6, < 3)
      options (~> 2.3.0)
    protocol-hpack (1.4.2)
    protocol-http (0.22.5)
    protocol-http1 (0.14.2)
      protocol-http (~> 0.22)
    protocol-http2 (0.14.2)
      protocol-hpack (~> 1.4)
      protocol-http (~> 0.18)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (4.0.6)
    puma (5.5.2)
      nio4r (~> 2.0)
    puma-status (1.3)
      colorize (~> 0.8)
      net_http_unix (~> 0.2)
      parallel (~> 1)
    racc (1.6.0)
    rack (2.2.3)
    rack-attack (6.5.0)
      rack (>= 1.0, < 3)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-protection (2.1.0)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.4.1)
      actioncable (= 6.1.4.1)
      actionmailbox (= 6.1.4.1)
      actionmailer (= 6.1.4.1)
      actionpack (= 6.1.4.1)
      actiontext (= 6.1.4.1)
      actionview (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activemodel (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      bundler (>= 1.15.0)
      railties (= 6.1.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (6.1.4.1)
      actionpack (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      method_source
      rake (>= 0.13)
      thor (~> 1.0)
    rake (13.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rbtrace (0.4.14)
      ffi (>= 1.0.6)
      msgpack (>= 0.4.3)
      optimist (>= 3.0.0)
    rchardet (1.8.0)
    rdoc (6.3.3)
    recaptcha (4.8.0)
      json
    recursive-open-struct (1.1.3)
    redis (4.5.1)
    regexp_parser (2.1.1)
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    request_store (1.5.0)
      rack (>= 1.4)
    retriable (3.1.2)
    rexml (3.2.5)
    rly (0.2.3)
    rmagick (4.2.3)
    rocketchat (0.1.21)
    rotp (6.2.0)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-rails (5.0.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      railties (>= 5.2)
      rspec-core (~> 3.10)
      rspec-expectations (~> 3.10)
      rspec-mocks (~> 3.10)
      rspec-support (~> 3.10)
    rspec-support (3.10.3)
    rswag (2.4.0)
      rswag-api (= 2.4.0)
      rswag-specs (= 2.4.0)
      rswag-ui (= 2.4.0)
    rswag-api (2.4.0)
      railties (>= 3.1, < 7.0)
    rswag-specs (2.4.0)
      activesupport (>= 3.1, < 7.0)
      json-schema (~> 2.2)
      railties (>= 3.1, < 7.0)
    rswag-ui (2.4.0)
      actionpack (>= 3.1, < 7.0)
      railties (>= 3.1, < 7.0)
    ruby-progressbar (1.11.0)
    ruby2_keywords (0.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    savon (2.11.2)
      akami (~> 1.2)
      builder (>= 2.1.2)
      gyoku (~> 1.2)
      httpi (~> 2.3)
      nokogiri (>= 1.4.0)
      nori (~> 2.4)
      wasabi (~> 3.4)
    seedbank (0.3.0)
    sentry-rails (4.8.1)
      railties (>= 5.0)
      sentry-ruby-core (~> 4.8.1)
    sentry-ruby (4.8.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      faraday (>= 1.0)
      sentry-ruby-core (= 4.8.1)
    sentry-ruby-core (4.8.1)
      concurrent-ruby
      faraday
    shellany (0.0.1)
    sidekiq (6.3.1)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    signet (0.16.0)
      addressable (~> 2.8)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.3)
    socketry (0.5.1)
      hitimes (~> 1.2)
    socksify (1.7.1)
    spork (0.9.2)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.1)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    string-obfuscator (0.1.3)
    test-unit (3.5.1)
      power_assert
    text (1.3.1)
    thor (1.1.0)
    tilt (2.0.10)
    timers (4.3.3)
    timfel-krb5-auth (0.8.3)
    tracking_number (0.10.5)
    trailblazer-option (0.1.2)
    twilio-ruby (3.16.1)
      builder (>= 2.1.2)
      jwt (~> 1.0)
      multi_json (>= 1.3.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8)
    wasabi (3.6.1)
      addressable
      httpi (~> 2.0)
      nokogiri (>= 1.4.2)
    waveinfo (0.0.5)
    webmock (3.14.0)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    webrick (1.7.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    wicked_pdf (2.1.0)
      activesupport
    will_paginate (3.3.1)
    wkhtmltopdf-binary (0.12.6.5)
    xmlrpc (0.3.2)
      webrick
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.1)
    zoom_rb (0.11.0)
      httparty (~> 0.13)
      json (>= 1.8)
      jwt

PLATFORMS
  x86_64-linux

DEPENDENCIES
  active_model_otp
  annotate
  asterisk-ajam (>= 0.0.2)
  bcrypt
  blanket_wrapper
  bootstrap-sass (= 2.3)
  bson_ext
  byebug
  cancancan
  cane
  capybara
  chronic_duration
  cloudflare!
  coffee-rails
  colorize
  credit_card_sanitizer
  database_cleaner
  didww-client
  doorkeeper (= 5.5.2)
  down
  erubis
  factory_bot_rails
  faker
  fast_gettext (= 1.8.0)
  fog-openstack
  font-awesome-sass
  gcm
  gelf
  gemoji
  gettext (>= 1.9.3)
  gettext_i18n_rails
  git
  google-api-client
  google-cloud-bigquery
  google-cloud-speech (~> 0.31)
  google-cloud-text_to_speech (~> 1.2)
  google-cloud-translate
  google-protobuf (~> 3.12)
  google_drive
  grpc (~> 1.31)
  guard-livereload
  guard-rspec
  guard-spork
  http
  jbuilder
  jquery-rails
  json
  locale
  lograge
  mimemagic (= 0.3.10)
  monit-client
  mysql2
  nokogiri
  omniauth-google-oauth2
  omniauth-kerberos
  omniauth-linkedin-oauth2
  omniauth-oauth2
  opensips-mi (>= 0.0.11)
  permanent_records (~> 3.1.6)
  phonelib
  progress_bar
  puma
  puma-status
  rack-attack
  rack-cors
  rails (= 6.1.4.1)
  rails-html-sanitizer
  rbtrace
  rdoc
  recaptcha (= 4.8.0)
  redis
  rmagick (~> 4.0)
  rocketchat
  rspec-rails
  rspec-support
  rswag
  rswag-api
  rswag-ui
  ruby-progressbar
  sass-rails
  seedbank (~> 0.3.0.pre2)
  sentry-rails
  sentry-ruby
  sidekiq
  simplecov
  sqlite3
  string-obfuscator
  test-unit (~> 3.0)
  twilio-ruby (~> 3.11)
  uglifier (>= 1.0.3)
  waveinfo
  webmock
  whenever
  wicked_pdf
  will_paginate
  wkhtmltopdf-binary
  xmlrpc
  zoom_rb

BUNDLED WITH
   2.2.32
```

**Comment by jeremyevans** [comment]
If you think this is a due to a bug in rack, can you please post a self contained example showing the problem?  Showing a bundler lock file with no code doesn't enable us to determine if the your problem is due to a bug in rack.  Looking at the backtrace, you have a broken rack application or middleware that is returning `nil` instead of enumerable as headers.  Since you say the problem isn't in your application, I would check all middleware between Rack::Deflater and the application in the middleware chain.

**Comment by julienchabanon** [comment]
Thank you @jeremyevans. I found the culprit! It was omniauth. Downgrading omniauth from 2.0.4 to 1.9.1 did solve the problem.

**Comment by wanglian** [comment]
having the same issue, but I don't think downgrading is a good solution 😆
