### ISSUE TITLE
can't rackup

### ISSUE THREAD

**Issue by columbian-chris** [rack/rack#2135]
Installed fresh out of the box and I get stuck when I try to `rackup`:

```
Traceback (most recent call last):
	20: from /usr/local/bin/rackup:23:in `<main>'
	19: from /usr/local/bin/rackup:23:in `load'
	18: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/bin/rackup:5:in `<top (required)>'
	17: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	16: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	15: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	14: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	13: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	12: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	11: from /var/lib/gems/2.7.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	10: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
	 9: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
	 8: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `new_from_string'
	 7: from /var/lib/gems/2.7.0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `eval'
	 6: from /srv/www/sandbox/public_html/test/truemail-rack/config.ru:3:in `block in <main>'
	 5: from /srv/www/sandbox/public_html/test/truemail-rack/config.ru:3:in `require_relative'
	 4: from /srv/www/sandbox/public_html/test/truemail-rack/config/loader.rb:3:in `<top (required)>'
	 3: from /srv/www/sandbox/public_html/test/truemail-rack/config/loader.rb:3:in `require_relative'
	 2: from /srv/www/sandbox/public_html/test/truemail-rack/config/system/types.rb:3:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- dry-types (LoadError)
```

**Comment by dentarg** [comment]
What does the code you run look like?

This doesn't look like a problem with Rack.

**Comment by jeremyevans** [comment]
Definitely not a problem with Rack itself, as Rack dose not use dry-types.

**Comment by jeremyevans** [comment]
Does your `config.ru` file contain the following, as the README instructs?:

```ruby
run do |env|
  [200, {}, ["Hello World"]]
end
```

**Comment by columbian-chris** [comment]
Yes, and that works on its own.  It's clearly not an issue with Rack.  Thank you for your answers.
