### ISSUE TITLE
Rack::Lint::LintError: Status must be >=100 seen as integer

### ISSUE THREAD

**Issue by lacostenycoder** [rack/rack#2136]
Ruby Version: 3.2.2
Rack Version: 2.2.8

I'm working on rack app that uses Websockets with ActionCable. It's non-rails, but uses Sinatra.

Here's my config.ru, I added some debugger info.  It seems that Websocket is being "upgraded" But returning a -1 status. 

```ruby
# frozen_string_literal: true
# File: config.ru
require_relative 'config/environment'
require 'sidekiq/web'
require 'puma/configuration'
require 'sinatra'
require 'action_cable'
#require_relative 'app/channels/endpoint_channel'

ActionCable.server.config.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/] unless ENV['RACK_ENV'] == 'production'
# get session key from file
use Rack::Session::Cookie, secret: File.read('config/.session_secret.key'), same_site: :strict, expire_after: 86400
# Basic authentication for Sidekiq Web UI
Sidekiq::Web.use(Rack::Auth::Basic, "Sidekiq Protected Area") do |username, password|
  # Protect against timing attacks:
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use `variable_size_secure_compare` to mitigate length attacks.
  Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
    Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
end if ENV['RACK_ENV'] == 'production' # Enable this only in production

# Add this middleware to your stack
class DebugMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    status, headers, body = @app.call(env)
    puts "Status: #{status}"
    puts "Headers: #{headers}"
    puts "Body: #{body.inspect}"
    [status, headers, body]
  end
end

# Then in your config.ru or equivalent
App = Rack::Builder.new do
  #use ErrorHandlingMiddleware
  map '/cable' do
    use DebugMiddleware
    run ActionCable.server
  end

  map '/' do
    use DebugMiddleware
    run Sinatra::Application
  end

  map '/sidekiq' do
    run Sidekiq::Web
  end
end

# Middleware for clean logging of requests
use Rack::CommonLogger

run App
```

Here's my log output showing the debugger info and the linter error:

```
11:49:08 web.1          | I, [2023-11-18T11:49:08.577860 #26620]  INFO -- : Started GET "/cable" [WebSocket] for 127.0.0.1 at 2023-11-18 11:49:08 -0500
11:49:08 web.1          | I, [2023-11-18T11:49:08.578087 #26620]  INFO -- : Started GET "/cable" [WebSocket] for 127.0.0.1 at 2023-11-18 11:49:08 -0500
11:49:08 web.1          | I, [2023-11-18T11:49:08.578137 #26620]  INFO -- : Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
11:49:08 web.1          | I, [2023-11-18T11:49:08.577969 #26620]  INFO -- : Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
11:49:08 web.1          | Status: -1
11:49:08 web.1          | Status: -1
11:49:08 web.1          | Headers: {}
11:49:08 web.1          | Body: []
11:49:08 web.1          | Headers: {}
11:49:08 web.1          | Body: []
11:49:08 web.1          | Rack::Lint::LintError: Status must be >=100 seen as integer
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/lint.rb:651:in `check_status'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/lint.rb:56:in `_call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/lint.rb:38:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/show_exceptions.rb:23:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/common_logger.rb:38:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:261:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/rack-2.2.8/lib/rack/content_length.rb:17:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'
11:49:08 web.1          |       /home/lance/dev/careg/github/APS_Adapter/vendor/cache/ruby/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by jeremyevans** [comment]
Is there a reason you think this is a bug in Rack?  If you are just asking for general help, you could post in Discussions, but the problem you are having does not appear related to Rack itself.  It's probably an issue in ActionCable.

**Comment by MSP-Greg** [comment]
I looked back thru Puma, and a commit [Add support for async socket handoff](https://github.com/puma/puma/commit/dd12ba39f3a468266c8c739a6605d28f91022284) (08-Jan-2012) checked whether `status == -1`.

WebSocket was finalized first in Dec-2011 with "IETF 6455 The WebSocket Protocol".

**Comment by lacostenycoder** [comment]
> Is there a reason you think this is a bug in Rack? If you are just asking for general help, you could post in Discussions, but the problem you are having does not appear related to Rack itself. It's probably an issue in ActionCable.

OK I wasn't sure but if it's not a Rack issue, I'll look elsewhere. Thanks.

**Comment by ioquatix** [comment]
@lacostenycoder IIUC, your question is, why does the lint reject `status=-1`?

https://github.com/rack/rack/blob/f6c583adb0e863e524bacedaf594602964e01078/lib/rack/lint.rb#L619-L625

I suppose in the past, `-1` was used to indicate "ignore this response" and was used when performing a full hijack. @jeremyevans not sure if we document it, but what should the user return when performing a full hijack?

**Comment by ioquatix** [comment]
According to https://github.com/rack/rack/blob/main/SPEC.rdoc#full-hijack- the response is ignored, so in theory you can return any valid status code, e.g. 200 okay, etc.

@jeremyevans should we consider allowing -1? or nil? I think the reason not to do this is because other middleware may not be aware of the full hijack. AFAIK, there is no mechanism to signal on the return path that the response is to be ignored.

**Comment by jeremyevans** [comment]
Make we should change `Lint` so that it doesn't check for response status if full hijack has been done?

**Comment by ioquatix** [comment]
The problem with this, is that all middleware needs to accommodate it on the return path. I think it would be better to document a standard for full hijack - either `-1` is acceptable as a status code and indicates the response is invalid, or something else? I suppose `-1` was chosen since it still compares correctly.

**Comment by jeremyevans** [comment]
I guess I'm OK for `-1` as status if full hijack is active.

**Comment by lacostenycoder** [comment]
So is this a case where perhaps this issue can be resolved in this repo? Because for now I used [this monkey patch](https://github.com/rails/rails/issues/26179#issuecomment-351721859) eek.

**Comment by ioquatix** [comment]
Please open a PR with the following changes:

- Explicitly document the response that should be returned when using full hijack.
- Let's add some tests and fix `Rack::Lint` to accept that.
