### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by 0llirocks** [rack/rack#2146]
ruby: 3.1.2
rails 7.1.3
puma: 6.4.2
rack: 3.0.8

config.ru with RAILS_RELATIVE_URL_ROOT=/app
```
# This file is used by Rack-based servers to start the application.

require_relative "config/environment"

map ENV['RAILS_RELATIVE_URL_ROOT'] do
    run Rails.application
end

Rails.application.load_server
```

Executing ```exec bundle exec puma``` results in following error:

```
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.1.2-p20) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 1
! Unable to load application: NoMethodError: undefined method `[]' for nil:NilClass

        unless location[0] == ?/
                       ^^^
bundler: failed to load command: puma (/usr/bin/puma)
/usr/share/gems/gems/rack-3.0.8/lib/rack/urlmap.rb:35:in `block in remap': undefined method `[]' for nil:NilClass (NoMethodError)

        unless location[0] == ?/
                       ^^^
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/urlmap.rb:27:in `each'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/urlmap.rb:27:in `map'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/urlmap.rb:27:in `remap'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/urlmap.rb:22:in `initialize'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:274:in `new'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:274:in `generate_map'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:252:in `to_app'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:105:in `new_from_string'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
        from /usr/share/gems/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/configuration.rb:368:in `load_rackup'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/configuration.rb:290:in `app'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/runner.rb:162:in `load_and_bind'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/single.rb:44:in `run'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
        from /usr/share/gems/gems/puma-6.4.2/lib/puma/cli.rb:75:in `run'
        from /usr/share/gems/gems/puma-6.4.2/bin/puma:10:in `<top (required)>'
        from /usr/bin/puma:25:in `load'
        from /usr/bin/puma:25:in `<top (required)>'
```

Any idea?

**Comment by dentarg** [comment]
I think `ENV['RAILS_RELATIVE_URL_ROOT']` is `nil`

Running this app leads to the same error as above

```ruby
require 'rack'
app = map nil do
  [200, {} ['OK']]
end
run app
```
