### ISSUE TITLE
TypeError in Request.params method

### ISSUE THREAD

**Issue by matas-zanevicius** [rack/rack#2223]
I came across this weird behaviour, and I did read through the other (closed) issues. I did not find an answer there, and I know how to replicate the error. Not a malformed POST request. And I know how to get around the issue, I just find it weird that it behaves like so.

I use:
rack (2.2.9)
roda (3.80.0)
rodauth (2.35.0)
rodauth-omniauth (0.3.4)

My Roda app:
```ruby
class App < Roda
  plugin :multi_run

  # root routes are required as multiple Roda apps

  route do |r|
    r.multi_run
  end
end
```
My Authorization Roda app
```ruby
class Authorization < Roda
  plugin :rodauth, json: :only, auth_class: Authentication::MyAuth

  App.run('auth') { self }

  route do |r|
    r.rodauth
  end
end
```
MyAuth class:
```ruby
module Authentication
  class MyAuth < Rodauth::Auth
    configure do
      enable :jwt, :login, :create_account, :omniauth
      
      omniauth_prefix '/social'
      omniauth_provider(secrets)
      
      omniauth_before_request_phase do
        # I want to take some actions based on params in my POST request body
        r.params
      end
    end
  end
end
```
If I send POST request with JSON body { "my_param": "my param value" } to /auth/social/google (request phase path)
I can get the r.params['my_param'] in my `:omniauth_before_request_phase` hook. But if I do so, it later causes Type error in Rack::Request#params. All is fine If I don't read the params in my hook.
It looks like that reading request params makes them `nil` for a sequential read from omniauth strategy.rb
```ruby
def request_call # rubocop:disable CyclomaticComplexity, MethodLength, PerceivedComplexity
 # [...]
  else
    if request.params[options.origin_param] 
      env['rack.session']['omniauth.origin'] = request.params[options.origin_param]
    elsif env['HTTP_REFERER'] && !env['HTTP_REFERER'].match(/#{request_path}$/)
      env['rack.session']['omniauth.origin'] = env['HTTP_REFERER']
    end

    request_phase
  end
rescue OmniAuth::AuthenticityError => e
  fail!(:authenticity_error, e)
end
```
My workaround is to dup the request in my hook and reed params from the dup.
But it still seems weird that I would need to do that.

Here is the backtrace of the error when I do read params from request in my hook:
TypeError: no implicit conversion of nil into Hash (the self.POST is nil)
```
"/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/request.rb:470:in `params'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/request.rb:32:in `params'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:252:in `request_call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:193:in `call!'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/request.rb:393:in `run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/run_handler.rb:36:in `block in run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/run_handler.rb:36:in `catch'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/run_handler.rb:36:in `run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:96:in `block in omniauth_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:151:in `block (2 levels) in omniauth_around_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:171:in `set_omniauth_jwt_session'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:159:in `set_omniauth_session'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:150:in `block in omniauth_around_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:182:in `set_omniauth_rodauth'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:149:in `omniauth_around_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:95:in `omniauth_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:49:in `route_omniauth!'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth.rb:40:in `route_omniauth!'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-omniauth-0.3.4/lib/rodauth/features/omniauth_base.rb:45:in `route!'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rodauth-2.35.0/lib/rodauth.rb:444:in `rodauth'",
 "/Users/mataszanevicius/my_app/routes/authorization.rb:108:in `block in <class:Authorization>'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:522:in `_roda_run_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:500:in `block in _roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:498:in `catch'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:498:in `_roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/error_handler.rb:88:in `_roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:384:in `block in base_rack_app_callable'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-attack-6.7.0/lib/rack/attack.rb:127:in `call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:53:in `call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/request.rb:393:in `run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/multi_run.rb:136:in `block in multi_run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/request.rb:603:in `if_match'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/request.rb:241:in `on'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/multi_run.rb:133:in `multi_run'",
 "/Users/mataszanevicius/my_app/app.rb:65:in `block in <class:App>'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:522:in `_roda_run_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/_before_hook.rb:27:in `_roda_run_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:500:in `block in _roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:498:in `catch'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:498:in `_roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda/plugins/error_handler.rb:88:in `_roda_handle_main_route'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:384:in `block in base_rack_app_callable'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/roda-3.80.0/lib/roda.rb:53:in `call'",
 "config.ru:10:in `block (2 levels) in <main>'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'",
 "/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"]
```

**Comment by jeremyevans** [comment]
This isn't really a Rack issue.  Rack::Request#params is not designed to handle JSON input.  Roda's json_parser plugin overrides `request.params` to handle JSON, but from the backtrace it appears that `omniauth` calls Rack::Request#params directly:

```
"/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/request.rb:32:in `params'",
"/Users/mataszanevicius/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:252:in `request_call'",
```

You'd probably have to request that `omniauth` handle JSON request bodies.
