### ISSUE TITLE
Headers with parameters which lack `=` raise a NoMethodError

### ISSUE THREAD

**Issue by AllyMarthaJ** [rack/rack#2250]
Hiya,

We're encountering an issue where we're receiving an unexpected error for a malformed header that we'd otherwise expect to default to something sensible. Take, for example, the following request:

```curl
curl -X POST https://somerackserver/rack -H "Content-Type:application/json;charset=" -d "{}" -vv
```

**ETA** we later realised down below the header being sent had `charset` not `charset=`

This is definitively malformed, but I'd have expected either `charset` to be `nil` or an empty string. 

In particular, the error comes from:
```
[
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:44:in `strip_doublequotes'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:37:in `block in params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `each'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `each_with_object'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/request.rb:451:in `media_type_params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/request.rb:459:in `content_charset'",
...
```

with the error `#<NoMethodError: No method 'start_with?' on instance of NilClass`

I'm happy to PR a fix to add guard for `nil` when calling `strip_doublequotes` here if that's all good!

Thanks!

**Comment by dentarg** [comment]
How to reproduce?

I tried this, but I don't see any problem.

```ruby
$ cat rack3.ru
app = lambda do |env|
  req = Rack::Request.new(env)
  pp req.content_type
  [200, {}, ["OK"]]
end

run app
```

```ruby
$ cat rack3.gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    nio4r (2.7.3)
    puma (6.4.3)
      nio4r (~> 2.0)
    rack (3.1.7)

PLATFORMS
  arm64-darwin-21
  ruby

DEPENDENCIES
  puma
  rack

BUNDLED WITH
   2.5.11
```

```shell
$ BUNDLE_GEMFILE=rack3.gemfile bundle exec puma rack3.ru
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.2.4-p170) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 1215
* Listening on http://0.0.0.0:9292
Use Ctrl-C to stop
"application/json;charset="
```

**Comment by AllyMarthaJ** [comment]
Errrr....yeah. I'm not able to reproduce with that example either. 🤦‍♀️

How bizarre. I'll try and reproduce without our stack, maybe there's something else in our middleware that's playing games with this.

**Comment by ioquatix** [comment]
Thanks for the great discussion so far. It would be great to have a working reproduction. Thanks for the effort to produce this so far. Once we can reproduce it, we can consider the best way to fix it.

**Comment by ioquatix** [comment]
Just touching base here - any update?

**Comment by AllyMarthaJ** [comment]
So sorry for the late reply—I've not been able to get to a repro. I'll close this for now.
(It's painful because it only happens once in a blue moon...)

**Comment by dentarg** [comment]
If it happens again, please share the full backtrace @AllyMarthaJ

**Comment by AllyMarthaJ** [comment]
Found the original full stacktrace, which includes our middleware (doesn't do anything special to the content charset headers in particular):
```
[
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:44:in `strip_doublequotes'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:37:in `block in params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `each'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `each_with_object'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/media_type.rb:33:in `params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/request.rb:451:in `media_type_params'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/request.rb:459:in `content_charset'",
  "/app/backend/lib-stile-ruby/lib/stile/enhanced_puma_request.rb:29:in `parsed_body'",
  "/app/backend/public-api2/lib/public_api/proto_http/handler.rb:525:in `block (2 levels) in build_handler'",
  "/app/backend/lib-stile-ruby/lib/stile/trace.rb:114:in `trace'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'",
  "/app/backend/public-api2/lib/public_api/proto_http/handler.rb:354:in `block in build_handler'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'",
  "(eval at /usr/local/lib64/ruby/gems/3.3.0/gems/http_router-0.11.2/lib/http_router/node/root.rb:36):15694:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'",
  "/app/backend/public-api2/lib/public_api/proto_http/handler.rb:105:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/urlmap.rb:76:in `block in call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/urlmap.rb:60:in `each'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/urlmap.rb:60:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/static.rb:161:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/client_timestamp.rb:49:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/profiling.rb:48:in `block in call'",
  "/app/backend/lib-stile-ruby/lib/stile/profiler.rb:68:in `profile'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/profiling.rb:27:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/tracing.rb:69:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/cursing.rb:80:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/auth.rb:26:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/load_shedding.rb:354:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/error_handling.rb:13:in `block in call'",
  "/app/backend/lib-stile-ruby/lib/stile/exception_handling.rb:137:in `block in with_rescue_handlers_outside_em'",
  "/app/backend/lib-stile-ruby/lib/stile/exception_handling.rb:106:in `with_rescue_handlers_inside_em'",
  "/app/backend/lib-stile-ruby/lib/stile/exception_handling.rb:137:in `with_rescue_handlers_outside_em'",
  "/app/backend/lib-stile-ruby/lib/stile/exception_handling.rb:11:in `with_rescue_handlers'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/error_handling.rb:13:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/log.rb:132:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/metrics.rb:417:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/cookie_parser.rb:55:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/global_correlation.rb:16:in `call'",
  "/app/backend/lib-stile-ruby/lib/stile/rack_middleware/client_ip_address.rb:35:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/slo_tracking.rb:160:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'",
  "/app/backend/public-api2/lib/public_api/middleware/header_encoding.rb:28:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/deflater.rb:47:in `call'",
  "/app/backend/public-api2/lib/public_api/app.rb:221:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:272:in `call'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:100:in `block in handle_request'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:378:in `with_force_shutdown'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:99:in `handle_request'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:464:in `process_client'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:245:in `block in run'",
  "/usr/local/lib64/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
]
```

**Comment by dentarg** [comment]
Oh, I called the wrong method in my attempt to repro this!

Check this out:

```shell
$ echo 'require "rack"; port 8080; app { |env| req = ::Rack::Request.new(env); pp req.content_charset; [200, {}, ["OK"]] }' | puma --config /dev/stdin --log-requests
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 60042
* Listening on http://0.0.0.0:8080
Use Ctrl-C to stop
""
127.0.0.1 - - [23/Nov/2024:10:48:07 +0100] "POST / HTTP/1.1" 200 - 0.0243
2024-11-23 10:48:23 +0100 Rack app ("POST /" - (127.0.0.1)): #<NoMethodError: undefined method `start_with?' for nil>
```

This request works: `curl localhost:8080 -H "Content-Type:application/json;charset=" -d "{}" -v`

but not this

```shell
$ curl localhost:8080 -H "Content-Type:application/json;charset" -d "{}" -v
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 60055 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
* using HTTP/1.x
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.10.1
> Accept: */*
> Content-Type:application/json;charset
> Content-Length: 2
>
* upload completely sent off: 2 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Length: 1858
<
Puma caught this error: undefined method `start_with?' for nil (NoMethodError)
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/media_type.rb:44:in `strip_doublequotes'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/media_type.rb:37:in `block in params'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/media_type.rb:33:in `each'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/media_type.rb:33:in `each_with_object'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/media_type.rb:33:in `params'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/request.rb:451:in `media_type_params'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/request.rb:459:in `content_charset'
/dev/stdin:1:in `block in _load_from'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/commonlogger.rb:47:in `call'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:272:in `call'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:100:in `block in handle_request'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:99:in `handle_request'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:464:in `process_client'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:245:in `block in run'
* Connection #0 to host localhost left intact
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by AllyMarthaJ** [comment]
Oh! Yesssss, sweet!

**Comment by AllyMarthaJ** [comment]
Your repro also has `charset` instead of `charset=` 👀

**Comment by dentarg** [comment]
Also a problem with current main branch (ecdce74686e991bdc50674194920ec0c0b8f3bd9) , tested with `echo '$LOAD_PATH.unshift("lib"); require "rack"; pp ::Rack::RELEASE; port 8080; app { |env| req = ::Rack::Request.new(env); pp req.content_charset; [200, {}, ["OK"]] }' | puma --config /dev/stdin --log-requests`

**Comment by ioquatix** [comment]
Does someone want to have a go at making a PR?

**Comment by AllyMarthaJ** [comment]
Will give it a shot!

**Comment by AllyMarthaJ** [comment]
I've given it a shot above: i'm not super tied to the semantics of what comes through (whether the key-value pair is omitted, for example, or the value is nil, or the value is an empty string)

**Comment by ioquatix** [comment]
Fixed by the above merge.
