### ISSUE TITLE
Rack::VERSION ?

### ISSUE THREAD

**Issue by trans** [rack/rack#256]
I want to think it something I am doing, but I don't see how. I upgraded to rack 1.3.4 and ran a little server that I had written sometime ago and worked fine in the past. But now I am getting:

```
[2011-10-17 18:15:48] ERROR NameError: uninitialized constant Rack::VERSION
    /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.3.4/lib/rack/handler/webrick.rb:40:in `service'
    /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
    /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /usr/local/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by MeetChavda** [comment]
remove this gem `gem 'rack-mini-profiler'
`
