### ISSUE TITLE
app error: deadlock; recursive locking (ThreadError) with Rack::Deflater

### ISSUE THREAD

**Issue by jonhyman** [rack/rack#658]
Last week, we moved some servers over to Rackspace's cloud and started getting a bunch of deadlocks (once every few minutes) in our application. Before I had seen this very very infrequently, and had read through various issues which describe people running into this when enabling `Rack::Deflater` (e.g., #349, https://gist.github.com/zporter/2936818).

We're using rack 1.4.5, I dug into the source code of the gem and confirmed that the body is getting closed.

However, I can now consistently reproduce a deadlock in our application when we `use Rack::Deflater` in our config.ru. If I remove it, I can no longer reproduce the deadlocks. I imagine that there might be something different about the Rackspace environment since the timing was too coincidental (and nothing else changed), but removing `Rack::Deflater` and gzipping via nginx fixes this for me.

```
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239518 #32444] ERROR -- : app error: deadlock; recursive locking (ThreadError)
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239683 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:14:in `lock'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239726 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:14:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239760 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.10/lib/action_dispatch/middleware/static.rb:62:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239793 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239826 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239858 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239904 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239939 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.239972 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/railties-3.2.10/lib/rails/engine.rb:479:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240004 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/railties-3.2.10/lib/rails/application.rb:223:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240035 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/railties-3.2.10/lib/rails/railtie/configurable.rb:30:in `method_missing'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240066 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240098 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240130 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240161 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/deflater.rb:13:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240192 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240224 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240255 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240286 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240317 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240348 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240380 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/gems/unicorn-4.8.2/bin/unicorn:126:in `<top (required)>'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240412 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
Feb 12 17:37:16 dashboard-app-st-02 stderr.log:  E, [2014-02-12T22:37:16.240443 #32444] ERROR -- : /var/www/dashboard/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'
```

```
bundle exec rake middleware

use Rack::Cache
use ActionDispatch::Static
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::RedisStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use ActionDispatch::Head
use Rack::ConditionalGet
use Rack::ETag
use ActionDispatch::BestStandardsSupport
use Warden::Manager
use OmniAuth::Builder
use Rack::Mongoid::Middleware::IdentityMap
run MyApp::Application.routes
```

**Comment by ioquatix** [comment]
The reason why this happens is because you enter into the same lock a 2nd time.

The reason why this happens is potentially because something within the locked part of your code, is triggering another request which eventually ends up trying to acquire the lock a 2nd time.

One option would be to remove the lock.

Another option would be to move the lock higher up in the middleware (above whatever is causing the 2nd request).

However, if you only have a limited number of threads available to handle requests, and you have some kind of cycle request, there is no way to avoid this in general.

Because this issue is very old and has not been updated for several years, I'm going to close it.

That being said, if you are still having issues, please feel free to discuss it here and we can consider re-opening it.
