### ISSUE TITLE
Multipart parser is improperly case-sensitive?

### ISSUE THREAD

**Issue by timothyekl** [rack/rack#676]
I've hit a case where I think Rack is failing to parse a multipart form POST because of the case of the Content-Type header value. I have the following data in a file `file.txt`:

```
--TEST
Content-Disposition: form-data; name="file"; filename="test"
Content-Type: text/plain

foo
bar
baz

--TEST--
```

I've written a simple Sinatra application that accepts POST requests to `/` and returns a plain string:

```
require 'sinatra'
post '/' do
  "success"
end
```

If I use the data in this file as the body of this POST request from curl, I see the "success" string as expected:

```
curl --data-binary @file.txt -H "Content-Type: Multipart/Form-Data; Boundary=TEST" localhost:9393
```

However, if I convert the value of that header to all lowercase and try again:

```
curl --data-binary @file.txt -H "Content-Type: multipart/form-data; boundary=TEST" localhost:9393
```

then I see an EOFError produced inside rack's `parser.rb`:

```
EOFError: bad content body
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:74:in `block in fast_forward_to_first_boundary'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:72:in `loop'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:72:in `fast_forward_to_first_boundary'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:15:in `parse'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/multipart.rb:25:in `parse_multipart'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/request.rb:377:in `parse_multipart'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/request.rb:203:in `POST'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:26:in `method_override'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:14:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'
/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'
/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

Is this actually a Rack error, or is my request malformed somehow?

**Comment by airblade** [comment]
@saurabh-g Please could you post a gist of your monkey patch?  I tried to patch my Rails 3.2 / Rack 1.4.7 app but can't get it to work.
