### ISSUE TITLE
JRuby tests failing

### ISSUE THREAD

**Issue by dblock** [rack/rack#778]
```
Bacon::Error: "location%5B%5D=1&location%5B%5D=2&age_group%5B%5D=2".==("location[]=1&location[]=2&age_group[]=2") failed
	/home/travis/build/dblock/rack/test/spec_mock.rb:35:in `(root)': Rack::MockRequest - should return an environment with a path
	org/jruby/RubyBasicObject.java:1641:in `instance_eval'
	/home/travis/build/dblock/rack/test/spec_mock.rb:33:in `(root)'
	org/jruby/RubyBasicObject.java:1641:in `instance_eval'
	/home/travis/build/dblock/rack/test/spec_mock.rb:21:in `(root)'
	org/jruby/RubyKernel.java:969:in `load'
	org/jruby/RubyArray.java:1567:in `each'
	org/jruby/RubyKernel.java:969:in `load'
	org/jruby/RubyKernel.java:990:in `eval'
	/home/travis/.rvm/gems/jruby-1.7.18-d19/bin/jruby_executable_hooks:15:in `__script__'
Bacon::Error: java.lang.IllegalArgumentException.instance_of?(Errno::EPIPE) failed
	/home/travis/build/dblock/rack/test/spec_multipart.rb:138:in `(root)': Rack::Multipart - should reject insanely long boundaries
	org/jruby/RubyBasicObject.java:1641:in `instance_eval'
	/home/travis/build/dblock/rack/test/spec_multipart.rb:89:in `(root)'
	org/jruby/RubyBasicObject.java:1641:in `instance_eval'
	/home/travis/build/dblock/rack/test/spec_multipart.rb:4:in `(root)'
	org/jruby/RubyKernel.java:969:in `load'
	org/jruby/RubyArray.java:1567:in `each'
	org/jruby/RubyKernel.java:969:in `load'
	org/jruby/RubyKernel.java:990:in `eval'
	/home/travis/.rvm/gems/jruby-1.7.18-d19/bin/jruby_executable_hooks:15:in `__script__'
```

On OSX with jruby-1.7.18 I cannot reproduce this.

**Comment by mkristian** [comment]
travis seems to be green - it this still an issue to be fixed on jruby ?

**Comment by deepj** [comment]
This issue can be closed /cc @spastorino

**Comment by spastorino** [comment]
Thanks guys!
