### ISSUE TITLE
Test suite failures

### ISSUE THREAD

**Issue by davexunit** [rack/rack#875]
I'm trying to build the rack gem for myself with Ruby 2.2.2, but 3 tests fail for very similar reasons.  Does anyone have an idea what might be wrong with my environment to cause this discrepancy in the byte count?

```
Bacon::Error: "bytes 22-33/239".==("bytes 22-33/193") failed
	test/spec_file.rb:135:in `block (2 levels) in <top (required)>': Rack::File - should return correct byte range in body
	test/spec_file.rb:128:in `block in <top (required)>'
	test/spec_file.rb:5:in `<top (required)>'

Bacon::Error: "bytes */239".==("bytes */193") failed
	test/spec_file.rb:145:in `block (2 levels) in <top (required)>': Rack::File - should return error for unsatisfiable byte range
	test/spec_file.rb:139:in `block in <top (required)>'
	test/spec_file.rb:5:in `<top (required)>'

Bacon::Error: "239".==("193") failed
	test/spec_file.rb:189:in `block (2 levels) in <top (required)>': Rack::File - should set Content-Length correctly for HEAD requests
	test/spec_file.rb:185:in `block in <top (required)>'
	test/spec_file.rb:5:in `<top (required)>'
```

**Comment by tenderlove** [comment]
Does this still happen on master?

**Comment by davexunit** [comment]
Running the minimal version of the test suite works on master.  I'll patiently await the next release.  Thanks! :)

```
Skipping Rack::Handler::CGI tests (lighttpd is required). Install lighttpd and try again.
Skipping Rack::Handler::FastCGI tests (FCGI is required). `gem install fcgi` and try again.
Skipping Rack::Session::Memcache tests. Start memcached and try again.
Skipping Rack::Handler::Thin tests (Thin is required). `gem install thin` and try again.
Run options: --seed 12001

# Running:

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 3.709100s, 195.7348 runs/s, 639.2385 assertions/s.

726 runs, 2371 assertions, 0 failures, 0 errors, 0 skips
```
