### ISSUE TITLE
Integration tests fail when using 1.6.3 (worked in 1.6.2)

### ISSUE THREAD

**Issue by remomueller** [rack/rack#896]
After updating to rack 1.6.3 (from 1.6.2), I get the following errors when running integration tests:

```
NavigationTest#test_friendly_url_forwarding_after_login:
ArgumentError: wrong number of arguments (2 for 1)
    test/integration/navigation_test.rb:27:in `block in <class:NavigationTest>'
```

Is there anything I need to change in my tests to work with rack 1.6.3?

Thanks!

Changing back to 1.6.2 fixed this issue, here's the [failing build](https://travis-ci.org/nsrr/www.sleepdata.org/builds/67414347), and the [passing build](https://travis-ci.org/nsrr/www.sleepdata.org/builds/67424261) on Travis-CI.

**Comment by Hermanverschooten** [comment]
I was just hit by the same error and traced it back to this commit d68b93a9922b8bbfd76d5c7bcf5b63f2aec8f36f.
It adds a second parameter to parse_query.
I believe it is supposed to call the protected method parse_query in the same class Request, but it calls ActionDispatch::Request.parse_query which only takes 1 parameter.

**Comment by rywall** [comment]
Same problem here.

**Comment by ericboehs** [comment]
:+1:

**Comment by mariochavez** [comment]
Same issue here with Rails 4.2.1

    Rendered /.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (22.7ms)
     Error during failsafe response: wrong number of arguments (2 for 1)   /.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/http/request.rb:338:in `parse_query'
    /.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/request.rb:191:in `GET'

**Comment by Kukunin** [comment]
I've encountered the same problem. The problem with rake 1.6.3. Here is the error

```
Started GET "/" for 127.0.0.1 at 2015-06-18 23:27:59 +0300

ArgumentError (wrong number of arguments (2 for 1)):
  actionpack (4.2.0) lib/action_dispatch/http/request.rb:338:in `parse_query'
  rack (1.6.3) lib/rack/request.rb:191:in `GET'
  actionpack (4.2.0) lib/action_dispatch/http/request.rb:300:in `GET'
  actionpack (4.2.0) lib/action_dispatch/http/parameters.rb:14:in `parameters'
  actionpack (4.2.0) lib/action_dispatch/http/filter_parameters.rb:37:in `filtered_parameters'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:22:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack (1.6.3) lib/rack/etag.rb:24:in `call'
  rack (1.6.3) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.3) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.3) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.3) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.3) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.3) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.3) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.3) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.3) lib/rack/lock.rb:17:in `call'
  rack (1.6.3) lib/rack/content_length.rb:15:in `call'
  rack (1.6.3) lib/rack/handler/webrick.rb:88:in `service'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (15.5ms)
Error during failsafe response: wrong number of arguments (2 for 1)
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/http/request.rb:338:in `parse_query'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/request.rb:191:in `GET'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/http/request.rb:300:in `GET'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/http/parameters.rb:14:in `parameters'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_negotiation.rb:59:in `formats'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/public_exceptions.rb:22:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/methodoverride.rb:22:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/runtime.rb:18:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/lock.rb:17:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/sendfile.rb:113:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/lock.rb:17:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/content_length.rb:15:in `call'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.3/lib/rack/handler/webrick.rb:88:in `service'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/kukunin/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by ericboehs** [comment]
I've put up a PR for master and 1-6 stable. Someone give it a test please. CI is passing and it's working for me. https://github.com/rack/rack/issues/898

**Comment by Hermanverschooten** [comment]
My tests pass with your PR :smile:

**Comment by ericboehs** [comment]
Looks like @matthewd resolved it by reverting https://github.com/rack/rack/pull/781. I smell a 1.6.4 brewing.

**Comment by danlo** [comment]
+1 Encountered same issue; downgrading to 1.6.2 fixed it.

**Comment by darbs** [comment]
:+1:

**Comment by tenderlove** [comment]
Just pushed a 1.6.4 that should fix this.  I'm really sorry for the disruption. :(

**Comment by ericboehs** [comment]
@tenderlove No problem Aaron. Thanks for the fix. <3

**Comment by ericboehs** [comment]
I think this can be closed now.

**Comment by zavan** [comment]
Thank you :heart:

**Comment by Hermanverschooten** [comment]
:smiley:  You rock!

**Comment by remomueller** [comment]
Thanks for the quick fix!

**Comment by danlo** [comment]
WOOT! Super quick fix turn around!  Thank you!
