### ISSUE TITLE
Error uploading binary files in Rails 4.2, Ruby 2.1.2

### ISSUE THREAD

**Issue by evgenylivensky** [rack/rack#905]
After migrating to rails 4.2 there was an error when upload png files from Unity3d app like this:

```c#
WWWForm form = new WWWForm();
form.AddField( "user_sid", sid, System.Text.Encoding.UTF8 );
form.AddBinaryData( "file", data, fileName, "image/png; charset=UTF-8" );
AddRequest( "path/to/upload", form, null, false );
```

In the server side:

```
ArgumentError (unknown encoding name - "utf-8"):
  rack (1.6.4) lib/rack/multipart/parser.rb:211:in `find'
  rack (1.6.4) lib/rack/multipart/parser.rb:211:in `block in tag_multipart_encoding'
  rack (1.6.4) lib/rack/multipart/parser.rb:207:in `each'
  rack (1.6.4) lib/rack/multipart/parser.rb:207:in `tag_multipart_encoding'
  rack (1.6.4) lib/rack/multipart/parser.rb:75:in `block (2 levels) in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:250:in `get_data'
  rack (1.6.4) lib/rack/multipart/parser.rb:74:in `block in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `loop'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `parse'
  rack (1.6.4) lib/rack/multipart.rb:25:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:375:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:207:in `POST'
  actionpack (4.2.1) lib/action_dispatch/http/request.rb:308:in `POST'
  actionpack (4.2.1) lib/action_dispatch/http/parameters.rb:14:in `parameters'
  actionpack (4.2.1) lib/action_dispatch/http/filter_parameters.rb:37:in `filtered_parameters'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:22:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  simple_captcha2 (0.3.4) lib/simple_captcha/middleware.rb:26:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  passenger (5.0.6) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.6) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.6) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

problem in quotes...

**Comment by mcantor** [comment]
Are you sure you're running Ruby 2.1.2? Every other issue I can find involving this error was resolved by upgrading from <= 1.9 to >= 2.0. Perhaps you ran system ruby instead of `bundle exec`.

**Comment by evgenylivensky** [comment]
Yes. The problem in quotes at line 211:


```
encoding = Encoding.find v if k == CHARSET
```
where 
```
v = "\"utf-8\""
```
```
~$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

~$ ruby -e 'Encoding.find "\"utf-8\""'
-e:1:in `find': unknown encoding name - "utf-8" (ArgumentError)
	from -e:1:in `<main>'
```

**Comment by mcantor** [comment]
The symptom is much clearer now, at least; the encoding is coming through as `"utf-8"` instead of just `utf-8`. Unfortunately, I don't think this will be diagnosable without more of your code. @evgenylivensky, would it be possible for you to provide a gist or public GitHub repo that reproduces this problem with a small slice of your codebase, running as much of the full end-to-end call stack as possible? I have no idea how Unity3d works, but right now it seems like the bug could be anywhere; even Passenger.

**Comment by evgenylivensky** [comment]
unity3d code (WWWForm class) generate multipart http request like this:

```
POST path/to/upload HTTP/1.1
X-Unity-Version: 4.6.7f1
Content-Type: multipart/form-data; boundary="DCUxGP7YJupYAgWvtEzroP1c0RShKSqE3o5mpsiG"
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.1.1; A210 Build/JRO03H)
Host: *****
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 1673131

--DCUxGP7YJupYAgWvtEzroP1c0RShKSqE3o5mpsiG
Content-Type: text/plain; charset="utf-8"
Content-disposition: form-data; name="user_sid"

bbf14f82-d2aa-4c07-9fb8-ca6714a7ea97
--DCUxGP7YJupYAgWvtEzroP1c0RShKSqE3o5mpsiG
Content-Type: image/png; charset=UTF-8
Content-disposition: form-data; name="file"; filename="b67879ed-bfed-4491-a8cc-f99cca769f94.png"

...
```
May be this issue in http library in unity3d ?

**Comment by evgenylivensky** [comment]
The same issue

[http://stackoverflow.com/questions/28634278/error-receiving-binary-files-in-rails-4-2-and-ruby-2-2-0](http://stackoverflow.com/questions/28634278/error-receiving-binary-files-in-rails-4-2-and-ruby-2-2-0)

**Comment by mcantor** [comment]
I am actually pretty naïve about specs, but if you refer to the [HTTP spec](http://www.w3.org/Protocols/rfc2616/rfc2616.txt) segment on the `Content-Type` header:

```
14.17 Content-Type

   The Content-Type entity-header field indicates the media type of the
   entity-body sent to the recipient or, in the case of the HEAD method,
   the media type that would have been sent had the request been a GET.

       Content-Type   = "Content-Type" ":" media-type

   Media types are defined in section 3.7. An example of the field is

       Content-Type: text/html; charset=ISO-8859-4

   Further discussion of methods for identifying the media type of an
   entity is provided in section 7.2.1.
```

You can see that there are no double-quotes around the charset. Also, `charset` is defined further up as a `token`, which is defined as being comprised of `<any CHAR except CTLs or separators>`.

So, it's possible that Unity3D is actually generating invalid `Content-Type` fields, and this is "expected behavior" from rack.

It would be good if someone with more experience handling this kind of issue weighed in here. Perhaps @chneukirchen, @raggi, or @tenderlove?

**Comment by pensan** [comment]
any updates on this issue?

**Comment by rahul** [comment]
Thank you for the fix. In which release can we expect this to go live?

**Comment by raggi** [comment]
@tenderlove can answer
