### ISSUE TITLE
Rack::File lint error for HEAD requests that 404 (response body should not be given)

### ISSUE THREAD

**Issue by edmorley** [rack/rack#945]
Using Rack v1.6.4 and Ruby v2.1.5p273.

config.ru:
```ruby
run Rack::Static.new(
  @app,
  :urls => [""],
  :index => 'index.html'
)
```

Then after running `rackup`:
```bash
[~/src]$ curl -I "http://localhost:9292/non-existent-file.txt"
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 39
X-Cascade: pass
Server: WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13)
Date: Wed, 09 Sep 2015 22:05:08 GMT
Connection: close
```

From the Rack logs:
```
::1 - - [09/Sep/2015:23:05:08 +0100] "HEAD /non-existent-file.txt HTTP/1.1" 404 39 0.0007
[2015-09-09 23:05:08] ERROR Rack::Lint::LintError: Response body was given for HEAD request, but should be empty
        /usr/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:20:in `assert'
        /usr/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:688:in `verify_content_length'
        /usr/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:716:in `each'
        /usr/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
        /usr/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:112:in `service'
        /usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

Whilst Rack::File correctly handles HEAD requests (ie by returning an empty body) for successfully served files:
https://github.com/rack/rack/blob/c28f271d0c91f45e13bfa8f07bed445ef91f41de/lib/rack/file.rb#L125-L126
```ruby
    def make_body request, path, range
      if request.head?
        []
      else
        ...
```

There is no such handling in `fail()`:
```ruby
    def fail(status, body, headers = {})
      body += "\n"
      [
        status,
        {
          ...
        }.merge!(headers),
        [body]
```

**Comment by jeremy** [comment]
For an immediate fix, wrap with `Rack::Head`.

Agree Rack::File should omit the body for failed HEAD responses.

**Comment by tgrindinger** [comment]
@jeremy - Ok to open another pull request with just this change or do you have some suggestions on how to make it better?

**Comment by jeremy** [comment]
Yes, would open a PR to address HEAD responses in particular 😁

**Comment by edmorley** [comment]
Many thanks @jeremy :-)

**Comment by edmorley** [comment]
Sorry and @tgrindinger !
